### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by lpryszcz** [Gabaldonlab/redundans#4]
- AUTOMATISATION
  - [x] estimate read limit
  - [x] refine insert size estimation for each iteration
  - [x] include optional genome assembly step, is it really needed?
  - [x] include `--resume` option
  -  installator (to assist less experienced users)
  - [x] INSTALL.sh: UNIX installer
  - [x] Docker image
  - [x] Alpine Linux: strip numpy and biopython
  - [ ] official conda package #27 [unofficial one](https://anaconda.org/genomedk/redundans)
- PERFORMANCE
  - [x] approximate aligner ie [minimap](https://github.com/lh3/minimap) #60
  - [x] [sorting .psl files in memory](9)
  - [x] memory-optimised
- SENSITIVITY
  - [x] better similarity search algorithm ie. LAST
  - [ ] include depth of coverage
  - [ ] calculate insert size on major orientation only
- Features
  - [x] Support for long reads (PacBio, Nanopore)
  - [x] [Logging to file](7)
  - [x] FastaIndex
  - [x] fasta2homozygous.py: report removed contigs
- Exceptions
  - [x] check LAST version
  - [ ] no read aligned due to very fragmented assembly
- Long-read scaffolding
 - [x] production version of pyScaf #51
 - [ ] excessive gaps when scaffolding pacbio reads
- Code
 - [x] Python3
 - [x] remove nonsense #81 
 - [ ] make sure single TMP is used across the pipeline #81 
- Output
 - [x] gfa support (low priority) #72

**Comment by lpryszcz** [comment]
automatically estimate read limit setting using homozygous assembly size after reduction
and assuming let's say 50bp reads

**Comment by mictadlo** [comment]
- Miss-assembly detection: [MisSEQuel](http://bioinformatics.oxfordjournals.org/content/31/12/i80.full.pdf+html)
- [GMcloser](http://bioinformatics.oxfordjournals.org/content/31/23/3733.full.pdf+html)

**Comment by margaretc-ho** [comment]
Is there any plan to fix the `excessive gaps when scaffolding pacbio reads`? I couldn't get redundans to gap close with the long reads, and ended up running MASURCA's samba `close_scaffold_gaps.sh` with my long reads in order to get the gaps closed. It took me a while to find the right tool to do this (had problems running other gap filling tools like Gapless, GAPPadder, and MindTheGap, none of which were satisfactory). Putting a note here in case it helps others.

**Comment by lpryszcz** [comment]
hi, we decided to focus redundans on short-read technologies, so we won't be adding any long-read related features in the future.
